
package wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BookStorageService", targetNamespace = "http://wsserver/", wsdlLocation = "http://localhost:1212/storage?wsdl")
public class BookStorageService
    extends Service
{

    private final static URL BOOKSTORAGESERVICE_WSDL_LOCATION;
    private final static WebServiceException BOOKSTORAGESERVICE_EXCEPTION;
    private final static QName BOOKSTORAGESERVICE_QNAME = new QName("http://wsserver/", "BookStorageService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1212/storage?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOOKSTORAGESERVICE_WSDL_LOCATION = url;
        BOOKSTORAGESERVICE_EXCEPTION = e;
    }

    public BookStorageService() {
        super(__getWsdlLocation(), BOOKSTORAGESERVICE_QNAME);
    }

    public BookStorageService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOOKSTORAGESERVICE_QNAME, features);
    }

    public BookStorageService(URL wsdlLocation) {
        super(wsdlLocation, BOOKSTORAGESERVICE_QNAME);
    }

    public BookStorageService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOOKSTORAGESERVICE_QNAME, features);
    }

    public BookStorageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookStorageService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BookStorage
     */
    @WebEndpoint(name = "BookStoragePort")
    public BookStorage getBookStoragePort() {
        return super.getPort(new QName("http://wsserver/", "BookStoragePort"), BookStorage.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookStorage
     */
    @WebEndpoint(name = "BookStoragePort")
    public BookStorage getBookStoragePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsserver/", "BookStoragePort"), BookStorage.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOOKSTORAGESERVICE_EXCEPTION!= null) {
            throw BOOKSTORAGESERVICE_EXCEPTION;
        }
        return BOOKSTORAGESERVICE_WSDL_LOCATION;
    }

}
